title: Ole Hexel
description: Research scientist at the Max Planck Institute for demographic research
email: lastname [at] demogr [dot] mpg [dot] de [dot] junk
orcid: 0000-0002-5862-9229   
github_username: ohexel
bluesky_username: olhxl.bsky.social  
mastodon_username: at oxl at mastodon.social
baseurl: "/"
theme: minima
plugins: 
    - jekyll-feed
    - jekyll-relative-links
relative_links:
  enabled:     true
  collections: true
